### ISSUE TITLE
Interacting with Server

### ISSUE THREAD

**Issue by Kennochas** [PassiveLemon/tmodloader1.4-docker#10]
Is there any way to interact with the server when its running? For instance, if I wanted to to save the server, as it does not seem to save when exiting the container.

**Comment by Kennochas** [comment]
adding --interactive appears to have let me do a docker attach Terraria, and then interact with the console.

**Comment by PassiveLemon** [comment]
If you run the docker with -i (in your case, --interactive. same thing), then yes, you can attach and run commands.

**Comment by PassiveLemon** [comment]
> If I wanted to to save the server, as it does not seem to save when exiting the container.

By the way, I do plan on somehow adding a feature that saves the server when shutting down the container but I'm not quite sure how that would work and still be able to interact and view the server logs from the docker desktop client.

**Comment by Kennochas** [comment]
I had found this container that does it but the rest. 

Maybe it will provide inspiration?

https://hub.docker.com/r/rfvgyhn/tmodloader

**Comment by PassiveLemon** [comment]
That's a very interesting way to do that. I'll look into that more. I'll see if I can get that working by the next release

**Comment by Kennochas** [comment]
https://github.com/rfvgyhn/tmodloader-docker

Thats the github if you didn't see it as well.

Good luck sir!
