### ISSUE TITLE
"You are not using the same version as the server": How to update the tmodloader server version? 

### ISSUE THREAD

**Issue by fredrikburmester** [PassiveLemon/tmodloader1.4-docker#12]
As the title says: How do I update the tmodloader version of the server? 

As of writing this, the latest version of tmodloader is `2022.9.47.1`, and the server uses `2022.8.54.4`. 

Thanks!

**Comment by fredrikburmester** [comment]
I downloaded tmodloader from [Github](https://github.com/tModLoader/tModLoader/releases), unzipped, copied and overwrote all files. Then I changed the version number in the `entrypoint.sh` file.  That did it, I think :) 

Maybe I could have just changed the version number and removed the Libraries folder? If what I did is the incorrect method, please inform me here in a comment.

**Comment by PassiveLemon** [comment]
tModloader was just updated today and I haven't had time to update this yet. I don't have a release for the newest version yet so changing the version tag wont download this github but it will still download the tModloader files. You will have to make the serverconfig.txt and modify the start-tModLoaderServer.sh yourself, though you can use mine for reference. I should be able to get this updated later today.

**Comment by PassiveLemon** [comment]
There's not really a correct method so I would delete everything that isn't a part of this github to be absolutely sure, but what you did should most likely be fine because it is overwriting. The version tag is only needed when its downloading the server.

I'll comment in this after I do update it.

**Comment by PassiveLemon** [comment]
Its been updated to 2022.9.47.4 if you want to check that out
