### ISSUE TITLE
MODPACK docker env variable?

### ISSUE THREAD

**Issue by fredrikburmester** [PassiveLemon/tmodloader1.4-docker#17]
How should the env variable to formatted? 

Help here would be appreciated. 

Should it be ex: `-e 'MODPACK'='/tmodloader/server/ModPacks/Calamity/Mods/enabled.json'` ?

**Comment by PassiveLemon** [comment]
No, just the name of the folder that you put into the modpacks directory

**Comment by fredrikburmester** [comment]
So `-e 'MODPACK'='Calamity` ?

**Comment by PassiveLemon** [comment]
If that is the name you set for the Modpack, yes. If it's just the name of a mod, then it won't work

**Comment by PassiveLemon** [comment]
I'll assume this issue is resolved. Open it back up if it's  not.
