### ISSUE TITLE
server doesnt start using 2023.06.25.20

### ISSUE THREAD

**Issue by fooooooooooooooo** [PassiveLemon/tmodloader1.4-docker#19]
I'm having the same issue you did here https://github.com/tModLoader/tModLoader/issues/3625 when using `2023.06.25.20`

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmodloader/server/Libraries/Native/Linux/*/tmp'.
```

the server starts fine when using `2022.09.47.57`

if i'm not mistaken the solution you found is in the dockerfile https://github.com/PassiveLemon/tmodloader1.4-docker/blob/master/Dockerfile#L15-L17

**Comment by PassiveLemon** [comment]
You are correct about that. I will back-port that fix, give me like 10 minutes.

**Comment by PassiveLemon** [comment]
What version of the container are you using? That fix is in version 2.0.1, you shouldn't have this issue if you are using that version.

**Comment by PassiveLemon** [comment]
Interestingly, I cannot get the container to run either, even with the older version where the patch should have worked. This appears to be a bug.

**Comment by PassiveLemon** [comment]
Sorry for the wait, I honestly kind of forgot about this issue. It appeared to be an issue with Alpine as the base of the Container but it should be fixed in the latest version of the container. FYI, the container system has completely changed so you will need to look at that.
