### ISSUE TITLE
Can not find mod packs - incorrect path 

### ISSUE THREAD

**Issue by fredrikburmester** [PassiveLemon/tmodloader1.4-docker#9]
I'm having trouble loading a mod and I think I'm inputting the path incorrectly and would like some help. 

I have copied a mod file into the ModPacks folder like so: `/server/ModPacks/Calamity/CalamityMod.tmod`. 

What should I put in the paths in the server config file? 

Thank you.

**Comment by fredrikburmester** [comment]
I've also tried to copy the entire mod folder named `2824688072` but that folder contains other folders called 2022.5, 2022.6, and 2022.7 which all contain a CalamityMod.tmod file each.   

I set the paths in the server config like so:
```
modpath=/server/ModPacks/2824688072/2022.7
modpack=/server/ModPacks/2824688072/workshop.json
```

**Comment by PassiveLemon** [comment]
In the server config file, just change the line to the name of your modpack that you put in the ModPacks folder, which I assume in your case is Calamity.
The first line is where the .tmods are and the second line is to the enabled.json. The .tmods are the mods (duh) and the enabled.json tells the server what mods to load.

Ex:
modpath=/server/ModPacks/Calamity/Mods/
modpack=/server/ModPacks/Calamity/Mods/enabled.json

It will not work without an enabled.json so follow the instructions under "Modpack" to get a usable modpack folder

**Comment by fredrikburmester** [comment]
This worked, thank you! But now I'm trying to add a second mod like so: `/server/ModPacks/Lights/Mods/` and `/server/ModPacks/Lights/Mods/enabled.json`, but then how should I add this second mod to the serverconfig file? Thanks!

**Comment by PassiveLemon** [comment]
The server config points to a mod pack. Not individual mods. A modpack is a collection of mods as the name would imply lol. Simply just add the mod to the mods folder in the modpack that you already have. You will need to update the enabled.json with the new mod as well. I recommend just getting all the mods you want, enable them all, and make and upload the modpack.

**Comment by PassiveLemon** [comment]
If you still need help, just re-post to this thread and I'll continue to help but for now, I'm going to close this. As of writing this, modpacks are broken so that could potentially pose as an issue.
